version: '3.8'

services:
  web:
    build: .
    volumes:
      - .:/app
      - ./media:/app/media
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - PYTHONUNBUFFERED=1
    command: >
      sh -c "python manage.py migrate &&
             gunicorn --bind 0.0.0.0:8000 object_detection.wsgi:application"

  redis:
    image: redis:7.0
    ports:
      - "6379:6379"